In [2]:
import numpy as np

a = np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [4]:
import numpy as np 

b = np.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [6]:
import numpy as np 
c = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
import numpy as np 
a = np.array([[0,1,2],[3,4,5]])

print(a)
print()
print(a + 3)
print()
print(a * 3)

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [8]:
import numpy as np 
b = np.array([[0,1,2], [3,4,5]])
c = np.array([[2,0,1], [5,3,4]])

print(b)
print()
print(c)
print()
print(b + c)
print()
print(b * c)

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


In [9]:
import numpy as np 

def my_func(x):
    y = x * 2 + 1
    return y 

a = np.array([[0,1,2],[3,4,5]])
b = my_func(a)
print(b)

[[ 1  3  5]
 [ 7  9 11]]


In [10]:
import numpy as np 
a = np.array([[0,1,2],[3,4,5]]) 

print(np.sum(a))
print(np.average(a))
print(np.max(a))
print(np.min(a))

15
2.5
5
0
